---
version: '3.8'

services:
  db:
    container_name: irembopg
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: irembo_admin
      POSTGRES_PASSWORD: Irembo1234!
      POSTGRES_DB: rembo
    volumes:
      - irmpgdata:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  olap:
    container_name: irembo_ch
    image: clickhouse/clickhouse-server
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
      - "9000:9000"

  jobmanager:
    container_name: irembo_flink_jm
    image: flink:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    container_name: irembo_flink_tm
    image: flink:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command:
      - taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager2:
    container_name: flink_tm2
    image: flink:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command:
      - taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

volumes:
  irmpgdata:

